defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: gta_d4rl_mujoco_trial
mode: train_diffusion
seed: 0
device: cuda:7

# Environment
normalize_reward: True
terminal_penalty: -100
discount: 1.0

# GTA
solver: ddpm
diffusion_steps: 128
sampling_steps: 128
embed_dim: 32
model_dim: 16
predict_noise: True
ema_rate: 0.999
diffusion_learning_rate: 0.0003
label_dropout: 0.25
augmentation_size: 5000

# Diffusion Training
diffusion_gradient_steps: 100
batch_size: 256
log_interval: 10
save_interval: 80

## Classifier Free Guidance
w_cfg: 2.0
temperature: 1.0

# RL Training
rl_gradient_steps: 1000000

# Inference
ckpt: latest
num_envs: 50
num_episodes: 3
use_ema: True

# hydra
hydra:
  job:
    chdir: false

